# Numpy 

In [1]:
#importing necessary library

In [3]:
!pip install numpy

import numpy as np

In [4]:
#Array Creation
a = np.array(10)
type(a)

numpy.ndarray

In [6]:
#zero dimensional array

z=np.array(10)
z.ndim

0

In [8]:
#One dimensional array

In [9]:
o = np.array([10,12,12,15])
o.ndim

1

In [10]:
#Two dimensionalarray

In [12]:
t = np.array([[10,10,12,14,15]])
t.ndim

2

In [14]:
#three dimensional array

In [15]:
th =np.array([[[10,12,14,15,16]]])
th.ndim

3

In [16]:
#change the data type of the array element

In [19]:
a= np.array([10,15,52,54],dtype='float')
print(a.dtype)
a

float64


array([10., 15., 52., 54.])

# Other ways of creating an array

1.arange

2.linspace

3.Zeros

4.Ones

5.Random

In [25]:
a= np.arange(1,21,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [27]:
a= np.linspace(1,5,15)
a

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [29]:
a= np.linspace(1,5,15,retstep=True)
a

(array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
        2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
        3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ]),
 0.2857142857142857)

In [31]:
z =np.zeros([2,2])
z

array([[0., 0.],
       [0., 0.]])

In [34]:
o =np.ones([5,5])
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
r = np.random.rand(5,5)
r

array([[0.58810288, 0.66335086, 0.44967063, 0.42207046, 0.51926042],
       [0.48021982, 0.93523306, 0.51713747, 0.01668991, 0.52638893],
       [0.9276967 , 0.59614678, 0.27619885, 0.62519172, 0.78885593],
       [0.82455101, 0.26266071, 0.25543578, 0.18006812, 0.29765664],
       [0.89759969, 0.09786986, 0.39560656, 0.64561953, 0.51001948]])

In [40]:
r = np.random.randint(5,size=10)
r

array([0, 0, 3, 1, 2, 2, 4, 3, 4, 2])

# Slicing and Indexing of an array

In [44]:
a =np.array([[1,2,3],[4,5,6]])

In [45]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
a[0,0]

1

In [47]:
a[1,2]

6

In [48]:
a[0,2]

3

In [49]:
a[0,1:]

array([2, 3])

In [50]:
a[0:,1:]

array([[2, 3],
       [5, 6]])

In [52]:
#1 and 6
a[[0,1],[0,2]]

array([1, 6])

In [53]:
#3 and 4

In [55]:
a[[0,1],[2,0]]

array([3, 4])

# Reshaping the  arrays

In [56]:
a = np.random.rand(5,2)

In [57]:
a

array([[0.10858347, 0.88147095],
       [0.89541618, 0.56408565],
       [0.29583195, 0.21704333],
       [0.23951432, 0.40165409],
       [0.02683261, 0.16443182]])

In [58]:
a.reshape(2,5)

array([[0.10858347, 0.88147095, 0.89541618, 0.56408565, 0.29583195],
       [0.21704333, 0.23951432, 0.40165409, 0.02683261, 0.16443182]])

In [59]:
a.reshape(1,10)

array([[0.10858347, 0.88147095, 0.89541618, 0.56408565, 0.29583195,
        0.21704333, 0.23951432, 0.40165409, 0.02683261, 0.16443182]])

In [60]:
a.reshape(10,1)

array([[0.10858347],
       [0.88147095],
       [0.89541618],
       [0.56408565],
       [0.29583195],
       [0.21704333],
       [0.23951432],
       [0.40165409],
       [0.02683261],
       [0.16443182]])

In [62]:
#When we don't know how much columns going to accomodate then pass -1
a.reshape(5,-1)

array([[0.10858347, 0.88147095],
       [0.89541618, 0.56408565],
       [0.29583195, 0.21704333],
       [0.23951432, 0.40165409],
       [0.02683261, 0.16443182]])

# Aggregate Function

The python numpy aggregate functions are sum,min,max,average,product,median, standard deviation, variance,percentile,corrcoef

In [64]:
a.min()

0.02683260891260475

In [65]:
a.std()

0.2914995498817203

In [66]:
a.var()

0.08497198758124554

In [67]:
a.mean()

0.37948643668265275

In [68]:
a.max()

0.8954161770969737

# Stacking

In [69]:
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8])

In [70]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 4, 5, 6, 7, 8])

In [71]:
np.vstack([a,b])

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])